services:
  # 1. Your Website
  web:
    build: .
    container_name: TM-Bata-Camera-Link
    restart: unless-stopped
    ports:
      - "7080:80"

  # 2. Your Cloudflare Tunnel
  tunnel:
    image: cloudflare/cloudflared
    container_name: cloudflared-tm-bata-camera-link
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}